"""config/constants.py - COMPLETE AND FINAL"""
from datetime import date, time
from enum import Enum
from typing import Dict, List, Set
import pytz

# TIMEZONES
TZ_INDIA = pytz.timezone("Asia/Kolkata")
TZ_US_EAST = pytz.timezone("US/Eastern")
TZ_UTC = pytz.utc

# MARKET HOURS
class MarketHours:
    def __init__(self, name: str, timezone, open_time: time, close_time: time, pre_open_time: time, pre_close_time: time):
        self.name = name
        self.timezone = timezone
        self.open_time = open_time
        self.close_time = close_time
        self.pre_open_time = pre_open_time
        self.pre_close_time = pre_close_time

NSE_HOURS = MarketHours(
    name="NSE",
    timezone=TZ_INDIA,
    open_time=time(9, 15),
    close_time=time(15, 30),
    pre_open_time=time(8, 45),
    pre_close_time=time(15, 0),
)

NYSE_HOURS = MarketHours(
    name="NYSE",
    timezone=TZ_US_EAST,
    open_time=time(9, 30),
    close_time=time(16, 0),
    pre_open_time=time(9, 0),
    pre_close_time=time(15, 30),
)


# WATCHLISTS
INDIA_WATCHLIST = ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS", "WIPRO.NS", "AXISBANK.NS", "KOTAKBANK.NS", "LT.NS", "BAJFINANCE.NS", "SBIN.NS", "ASIANPAINT.NS", "TITAN.NS", "NESTLEIND.NS", "DMART.NS"]
US_WATCHLIST = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "JPM", "V", "MA", "NFLX", "ADBE"]

# UNIFIED COMPANY NAMES
WATCHLIST_COMPANY_NAMES = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "INFY.NS": "Infosys",
    "ICICIBANK.NS": "ICICI Bank",
    "WIPRO.NS": "Wipro",
    "AXISBANK.NS": "Axis Bank",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "LT.NS": "Larsen Toubro",
    "BAJFINANCE.NS": "Bajaj Finance",
    "SBIN.NS": "State Bank of India",
    "ASIANPAINT.NS": "Asian Paints",
    "TITAN.NS": "Titan Company",
    "NESTLEIND.NS": "Nestle India",
    "DMART.NS": "DMart Avenue Supermarts",
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "GOOGL": "Google Alphabet",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta Facebook",
    "TSLA": "Tesla",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "MA": "Mastercard",
    "NFLX": "Netflix",
    "ADBE": "Adobe",
}

# POSITION SIZING & RISK
POSITION_RISK_PCT = 0.02
MAX_POSITION_SIZE_PCT = 0.20
MIN_POSITION_SIZE_PCT = 0.01
MAX_OPEN_POSITIONS = 10
MAX_PORTFOLIO_HEAT = 5.0
MIN_RISK_REWARD_RATIO = 1.5
STOP_LOSS_ATR_MULTIPLIER = 2.0
TAKE_PROFIT_ATR_MULTIPLIER = 3.0
MAX_SECTOR_CONCENTRATION = 1.0
MAX_SECTOR_CONCENTRATION_PCT = 30.0
MAX_DAILY_LOSS_PCT = 0.05
MAX_DRAWDOWN_PCT = 0.15
MAX_LEVERAGE = 1.0
MIN_POSITION_VALUE = 5000
MIN_TRADE_VALUE = 5000
MIN_TRADE_VALUE_INR = 5000
MIN_TRADE_VALUE_USD = 100
MAX_POSITION_VALUE = 100000

# XGBOOST
XGBOOST_TARGET_RETURN_PCT = 0.01
XGBOOST_TARGET_DAYS = 5
XGBOOST_MAX_DEPTH = 6
XGBOOST_LEARNING_RATE = 0.1
XGBOOST_N_ESTIMATORS = 100
XGBOOST_MIN_CHILD_WEIGHT = 1
XGBOOST_GAMMA = 0
XGBOOST_SUBSAMPLE = 0.8
XGBOOST_COLSAMPLE_BYTREE = 0.8
XGBOOST_RANDOM_STATE = 42
XGBOOST_EARLY_STOPPING_ROUNDS = 10
XGBOOST_EVAL_METRIC = 'auc'
XGBOOST_USE_LABEL_ENCODER = False
XGBOOST_BUY_RETURN_THRESHOLD = 0.03
XGBOOST_SELL_RETURN_THRESHOLD = -0.03

# LSTM
LSTM_SEQUENCE_LENGTH = 60
LSTM_UNITS = 50
LSTM_DROPOUT = 0.2
LSTM_RECURRENT_DROPOUT = 0.2
LSTM_LEARNING_RATE = 0.001
LSTM_BATCH_SIZE = 32
LSTM_EPOCHS = 100
LSTM_VALIDATION_SPLIT = 0.2
LSTM_PATIENCE = 10
LSTM_LAYER_1_UNITS = 128
LSTM_LAYER_2_UNITS = 64
LSTM_DENSE_UNITS = 32
LSTM_DROPOUT_RATE = 0.2
LSTM_OUTPUT_CLASSES = 3
LSTM_MAX_EPOCHS = 100
LSTM_EARLY_STOPPING_PATIENCE = 10
LSTM_FEATURE_COUNT = 6

# ENSEMBLE
ENSEMBLE_LSTM_WEIGHT = 0.5
ENSEMBLE_XGBOOST_WEIGHT = 0.5
ENSEMBLE_MIN_AGREEMENT = 0.6
ENSEMBLE_MIN_DISAGREEMENT = 0.3
ENSEMBLE_BUY_THRESHOLD = 0.65
ENSEMBLE_SELL_THRESHOLD = 0.35
ENSEMBLE_CONFIDENCE_THRESHOLD = 0.6
ENSEMBLE_DISAGREEMENT_THRESHOLD = 0.4

# DECISION WEIGHTS & THRESHOLDS
DECISION_CONFIDENCE_THRESHOLD = 0.65
DECISION_BUY_THRESHOLD = 0.65
DECISION_SELL_THRESHOLD = 0.35
DECISION_HOLD_THRESHOLD = 0.50
DECISION_TECHNICAL_WEIGHT = 0.25
DECISION_FUNDAMENTAL_WEIGHT = 0.25
DECISION_SENTIMENT_WEIGHT = 0.25
DECISION_ML_WEIGHT = 0.25
DECISION_MIN_SCORE = 0.0
DECISION_MAX_SCORE = 10.0

# FEATURES
TECHNICAL_INDICATORS_WINDOW = 14
FUNDAMENTAL_LOOKBACK_DAYS = 252
MIN_TRAINING_SAMPLES = 100
FEATURE_SELECTION_THRESHOLD = 0.01

# ML TRAINING
ML_MIN_TRAINING_DAYS = 252
ML_TRAINING_PERIOD = "5y"
ML_INFERENCE_PERIOD = "3mo"
MIN_TRADING_DAYS_HISTORY = 252
MAX_CONSECUTIVE_MISSING_DAYS = 5
BACKTEST_MIN_SHARPE = 1.0
BACKTEST_MAX_DRAWDOWN = 25.0
BACKTEST_MIN_WIN_RATE = 0.50
BACKTEST_MIN_PROFIT_FACTOR = 1.2

# TECHNICAL ANALYSIS
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_LOWER_NEUTRAL = 45
RSI_UPPER_NEUTRAL = 55
BB_LOWER_ZONE = 0.20
BB_UPPER_ZONE = 0.80
VOLUME_SURGE_STRONG = 2.0
VOLUME_SURGE_MODERATE = 1.5
PRICE_AT_LEVEL_THRESHOLD = 0.02
NEAR_SUPPORT_THRESHOLD = 0.02
NEAR_RESISTANCE_THRESHOLD = 0.02
SMA200_AT_THRESHOLD = 0.02

# FUNDAMENTAL
FUNDAMENTAL_PE_MAX = 25.0
FUNDAMENTAL_DEBT_EQUITY_MAX = 1.0
FUNDAMENTAL_REVENUE_GROWTH_MIN = 10.0
FUNDAMENTAL_PROFIT_MARGIN_MIN = 15.0
FUNDAMENTAL_ROE_MIN = 15.0
FUNDAMENTAL_MIN_METRICS = 3

# MARKET REGIME
class MarketRegime(str, Enum):
    STRONG_BULL = "STRONG_BULL"
    BULL = "BULL"
    NEUTRAL = "NEUTRAL"
    BEAR = "BEAR"
    STRONG_BEAR = "STRONG_BEAR"

REGIME_POSITION_MULTIPLIER = {
    MarketRegime.STRONG_BULL: 1.0,
    MarketRegime.BULL: 0.8,
    MarketRegime.NEUTRAL: 0.6,
    MarketRegime.BEAR: 0.4,
    MarketRegime.STRONG_BEAR: 0.0,
}

VIX_LOW = 15.0
VIX_MODERATE = 20.0
VIX_HIGH = 25.0
VIX_VERY_HIGH = 35.0
VIX_EXTREME = 40.0

# DATA VALIDATION
PRICE_MAX_AGE_MINUTES = 15
PRICE_MAX_AGE_EOD_MINUTES = 60
PRICE_SPIKE_THRESHOLD = 0.20
MIN_DAILY_VOLUME = 100_000
MIN_DAILY_VOLUME_US = 500_000
MIN_NEWS_ARTICLES = 1
MIN_NEWS_ARTICLES_FOR_SENTIMENT = 3

# EARNINGS
class EarningsRiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    HIGH = "HIGH"
    BLOCK = "BLOCK"

EARNINGS_BLOCK_HOURS = 24
EARNINGS_HIGH_RISK_HOURS = 72
EARNINGS_LOW_RISK_DAYS = 7

# CIRCUIT BREAKER
CIRCUIT_BREAKER_CONSECUTIVE_LOSSES = 5
CIRCUIT_BREAKER_RUNAWAY_ORDERS = 20
CIRCUIT_BREAKER_DATA_FEED_TIMEOUT_MINS = 30
CIRCUIT_BREAKER_BROKER_TIMEOUT_MINS = 15
CIRCUIT_BREAKER_VIX_THRESHOLD = 40.0

# FRED
FRED_SERIES = {
    "federal_funds_rate": "FEDFUNDS",
    "gdp_growth": "A191RL1Q225SBEA",
    "unemployment": "UNRATE",
    "cpi_inflation": "CPIAUCSL",
    "treasury_10y": "DGS10",
    "treasury_2y": "DGS2",
    "yield_curve": "T10Y2Y",
    "consumer_sentiment": "UMCSENT",
    "industrial_production": "INDPRO",
}

# INDEX SYMBOLS
NIFTY_50_SYMBOL = "^NSEI"
NIFTY_BANK_SYMBOL = "^NSEBANK"
SENSEX_SYMBOL = "^BSESN"
SP500_SYMBOL = "^GSPC"
VIX_SYMBOL = "^VIX"
NASDAQ_SYMBOL = "^IXIC"
DOW_SYMBOL = "^DJI"

# SECTORS
NSE_SECTOR_MAP = {
    "RELIANCE.NS": "Energy",
    "TCS.NS": "IT",
    "HDFCBANK.NS": "Banking",
    "INFY.NS": "IT",
    "ICICIBANK.NS": "Banking",
    "WIPRO.NS": "IT",
    "AXISBANK.NS": "Banking",
    "KOTAKBANK.NS": "Banking",
    "LT.NS": "Infrastructure",
    "BAJFINANCE.NS": "NBFC",
    "SBIN.NS": "Banking",
    "ASIANPAINT.NS": "Consumer",
    "TITAN.NS": "Consumer",
    "NESTLEIND.NS": "FMCG",
    "DMART.NS": "Retail",
}

# TIMEOUTS
AGENT_TIMEOUT_SECONDS = {"PriceAgent": 30, "NewsAgent": 45, "MacroAgent": 60, "DecisionAgent": 60, "ExecutionAgent": 30}
DB_POOL_SIZE = 5
DB_MAX_OVERFLOW = 10
DB_POOL_TIMEOUT = 30